# Generated by Django 3.1.4 on 2020-12-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getid', models.IntegerField(verbose_name='上の数字を入力してください。')),
                ('get', models.CharField(max_length=50, verbose_name='アイテム数(例)1LC1st1個)')),
                ('discord', models.CharField(max_length=50, verbose_name='discord(例)ヨッピ太郎#1234)')),
                ('mcid', models.CharField(max_length=50, verbose_name='mcid(例)Yoppychan)')),
            ],
        ),
        migrations.CreateModel(
            name='lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='名前')),
                ('money', models.FloatField(verbose_name='金額')),
            ],
        ),
    ]
